
@startuml
hide empty methods
hide empty fields

modelTypes.size = 12


class "**RamdonDefaultConfig**" as RamdonDefaultConfig {
        IntegerType defaultElemCount
        IntegerType defaultTypeDepth
        IntegerType defaultMinArrayElemCount
        IntegerType defaultMaxArrayElemCount
        DateTimeType defaultMinDate
        DateTimeType defaultMaxDate
}

 

class "**RandomDataTypeConf**" as RandomDataTypeConf {
        IntegerType randMinElemCount
        IntegerType randMaxElemCount
        IntegerType randElemCount
        IntegerType randTypeDepth
}
note top: can put on schema types\nto include them in the\nrandom data generation

 

class "**RandomDataPropertyConf**" as RandomDataPropertyConf {
        BooleanType randIgnore
        RandomArrayConf randArrayConf
        ObjectType[] randValuePool
        RandomPropertyTypeConf randValueConf
}
note top: can put on schema properties\nto taylormade the random data\ngeneration

 

class "**RandomArrayConf**" as RandomArrayConf {
        IntegerType randMinElemCount
        IntegerType randMaxElemCount
        IntegerType randElemCount
}
note top: Processing information to create random\narrays

 

class "**RandomPropertyTypeConf**" as RandomPropertyTypeConf {
        RandomComplexTypeConf complexTypeConf
        RandomStringTypeConf stringTypeConf
        RandomNumTypeConf numTypeConf
        RandomDateTypeConf dateTypeConf
        RandomTimeTypeConf timeTypeConf
        RandomDurationTypeConf durationTypeConf
}

 

class "**RandomComplexTypeConf**" as RandomComplexTypeConf {
        IntegerType typeDepth
}
note top: Constraints to generate random values\nof a complex type

 

class "**RandomStringTypeConf**" as RandomStringTypeConf {
        RandomStringTypeConfStrTypeEnum strType
        IntegerType maxLength
}
note top: Constraints to generate random string\nvalues

 

class "**RandomNumTypeConf**" as RandomNumTypeConf {
        IntegerType minValue
        IntegerType maxValue
}
note top: Constraints to generate random numeric\nvalues

 

class "**RandomDateTypeConf**" as RandomDateTypeConf {
        DateTimeType minValue
        DateTimeType maxValue
}
note top: Constraints to generate random date\nvalues, used for dates and\ndate-times

 

class "**RandomTimeTypeConf**" as RandomTimeTypeConf {
        TimeType minValue
        TimeType maxValue
}
note top: Constraints to generate random time\nvalues

 

class "**RandomDurationTypeConf**" as RandomDurationTypeConf {
        DurationType minValue
        DurationType maxValue
}
note top: Constraints to generate random duration\nvalues

 

enum "RandomStringTypeConfStrTypeEnum" as RandomStringTypeConfStrTypeEnum {
    NAME
    ADDRESS
    EMAIL
    URL
    PHONE
    COUNTRY
    TEXT
    SENTENCE
}


    






    




    

RandomDataPropertyConf  *--  RandomArrayConf


RandomDataPropertyConf  *--  RandomPropertyTypeConf

    



    
RandomPropertyTypeConf  *--  RandomComplexTypeConf

RandomPropertyTypeConf  *--  RandomStringTypeConf

RandomPropertyTypeConf  *--  RandomNumTypeConf

RandomPropertyTypeConf  *--  RandomDateTypeConf

RandomPropertyTypeConf  *--  RandomTimeTypeConf

RandomPropertyTypeConf  *--  RandomDurationTypeConf

    

    


    


    


    


    


    

footer \ngenerated with yacg (https://github.com/OkieOth/yacg),\n(template: plantUml.mako v1.1.0)\npowered by plantuml (https://plantuml.com/)
@enduml