name: yacg actions lib

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv flake8
        pipenv --python 3.8
        pipenv --three install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics --per-file-ignores='yacg/model/*.py:E501 E303 W391'
    - name: Test with pytest
      run: |
        pipenv run python3 -m unittest discover tests "test_*.py"
    - name: Test run from command line
      run: |
        pipenv run python3 yacg.py \
            --models resources/models/json/yacg_config_schema.json \
                    resources/models/json/yacg_model_schema.json \
            --singleFileTemplates plantUml=stdout
    - name: Test run from command line
      run: |
        bin/demoMultiFileGenerator.sh
    - name: Test run from command line
      run: |
        bin/generateRandomData_example.sh
